// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var AwsAppsync = require("aws-appsync");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

var config = {
  graphqlEndpoint: "https://l3p3hundbrfp5f52rf2nj3mqsm.appsync-api.eu-west-1.amazonaws.com/graphql",
  region: "eu-west-1",
  authenticationType: "API_KEY",
  apiKey: "da2-gdjsycubkjdzjmi2bzyzjoyjaa"
};

var AppSyncConfig = /* module */[/* config */config];

function createAWSAppSyncClient(url, region, auth, param) {
  return new AwsAppsync.AWSAppSyncClient({
              url: Js_null_undefined.fromOption(url),
              region: Js_null_undefined.fromOption(region),
              auth: Js_null_undefined.fromOption(auth)
            });
}

var AppSync = /* module */[/* createAWSAppSyncClient */createAWSAppSyncClient];

exports.AppSyncConfig = AppSyncConfig;
exports.AppSync = AppSync;
/* aws-appsync Not a pure module */
