// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var AWS$ReactTemplate = require("./AWS.bs.js");

var instance = AWS$ReactTemplate.AppSync[/* createAWSAppSyncClient */0](AWS$ReactTemplate.AppSyncConfig[/* config */0].graphqlEndpoint, AWS$ReactTemplate.AppSyncConfig[/* config */0].region, {
      type: AWS$ReactTemplate.AppSyncConfig[/* config */0].authenticationType,
      apiKey: AWS$ReactTemplate.AppSyncConfig[/* config */0].apiKey
    }, /* () */0);

exports.instance = instance;
/* instance Not a pure module */
