// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var $$String = require("bs-platform/lib/js/string.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Utils$ReactTemplate = require("./Utils.bs.js");
var Search$ReactTemplate = require("./components/Search.bs.js");
var ListIceCreams$ReactTemplate = require("./components/ListIceCreams.bs.js");
var SearchIceCreams$ReactTemplate = require("./components/SearchIceCreams.bs.js");

((require('./styles/App.css')));

function changeSearch(send) {
  var update = Utils$ReactTemplate.Debounce[/* make */0](250, undefined, (function (newValue) {
          return Curry._1(send, /* ChangeSearch */[newValue]);
        }));
  return (function (newValue) {
      return Utils$ReactTemplate.Debounce[/* call */1](newValue, update);
    });
}

function reducer(action, _state) {
  return /* Update */Block.__(0, [/* record */[/* search */$$String.lowercase(action[0])]]);
}

function initialState(param) {
  return /* record */[/* search */""];
}

var component = ReasonReact.reducerComponent("App-ReactTemplate");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var search = param[/* state */1][/* search */0];
              var tmp = search === "" ? ReasonReact.element(undefined, undefined, ListIceCreams$ReactTemplate.make(/* array */[])) : ReasonReact.element(undefined, undefined, SearchIceCreams$ReactTemplate.make(search, /* array */[]));
              return React.createElement("div", {
                          className: "App"
                        }, ReasonReact.element(undefined, undefined, Search$ReactTemplate.make(undefined, changeSearch(param[/* send */3]), /* array */[])), tmp);
            }),
          /* initialState */initialState,
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.changeSearch = changeSearch;
exports.reducer = reducer;
exports.initialState = initialState;
exports.component = component;
exports.make = make;
/*  Not a pure module */
