// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';


function iceCreamToJs(param) {
  return {
          id: param[/* id */0],
          name: param[/* name */1],
          description: param[/* description */2],
          rating: param[/* rating */3]
        };
}

function iceCreamFromJs(param) {
  return /* record */[
          /* id */param.id,
          /* name */param.name,
          /* description */param.description,
          /* rating */param.rating
        ];
}

exports.iceCreamToJs = iceCreamToJs;
exports.iceCreamFromJs = iceCreamFromJs;
/* No side effect */
