// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Styles$ReactTemplate = require("./Styles.bs.js");

var component = ReasonReact.reducerComponent("Search");

function reducer(action, _state) {
  return /* Update */Block.__(0, [/* record */[/* value */action[0]]]);
}

function make($staropt$star, $staropt$star$1, _children) {
  var initialValue = $staropt$star !== undefined ? $staropt$star : "";
  var onChange = $staropt$star$1 !== undefined ? $staropt$star$1 : (function (_newValue) {
        return /* () */0;
      });
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              return React.createElement("div", undefined, React.createElement("input", {
                              style: Styles$ReactTemplate.inputStyle,
                              placeholder: "Search for ice cream",
                              value: param[/* state */1][/* value */0],
                              onChange: (function (e) {
                                  var value = e.target.value;
                                  Curry._1(send, /* ChangeValue */[value]);
                                  return Curry._1(onChange, value);
                                })
                            }));
            }),
          /* initialState */(function (param) {
              return /* record */[/* value */initialValue];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.reducer = reducer;
exports.make = make;
/* component Not a pure module */
